### ISSUE TITLE
enum Day.stingToDay(String str) cannot detect wrong input string that start with MTWRFS

### ISSUE THREAD

**Issue by tkwong94** [vicksonzero/TimetablePacker#13]
Fixed as:

 public static Day stringToDay(String str) throws WrongFormatException{
        //Converting String to char for switch statement so that it can be run with JDK 1.6
        if (str.length()>1)
            throw new WrongFormatException("Day should be one of MTWRFS");
        char str2=str.charAt(0);
        switch(str2){
        case 'M': return Day.MONDAY;
        case 'T': return Day.TUESDAY;
        case 'W': return Day.WEDNESDAY;
        case 'R': return Day.THURSDAY;
        case 'F': return Day.FRIDAY;
        case 'S': return Day.SATURDAY;
        default: throw new WrongFormatException("Day should be one of MTWRFS");
        }
    }

**Comment by tkwong94** [comment]
updated code.

**Comment by vicksonzero** [comment]
tkwong94 has finished this feature
