### ISSUE TITLE
Code Refactoring: Timetable.meetings shd be private instead of public

### ISSUE THREAD

**Issue by tkwong94** [vicksonzero/TimetablePacker#15]
Timetable.meetings shd be private instead of public.  To call the array, please go through Timetable.getMeetings();

**Comment by tkwong94** [comment]
Addtional: instances under Course class should all be corrected to private instead of public
Constructor of Course class should be added and pass course code in the method.

**Comment by tkwong94** [comment]
All the above three are updated.

**Comment by vicksonzero** [comment]
thwong has finished this feature
